//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;
namespace MI_WorkPlan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMiProject
    {
        public int projectId { get; set; }
        [Required]
        public string ProjectName { get; set; }
         [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
        public System.DateTime CreatedOn { get; set; }
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
        public System.DateTime UpdatedOn { get; set; }
        public string Notes { get; set; }
        public bool Active { get; set; }        
        [Required]
        public string Role { get; set; }
    }

}
