//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;
namespace MI_WorkPlan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMiProjectTask
    {
        public int taskId { get; set; }
        public int projectId { get; set; }
          [Required]
        public string TaskName { get; set; }
          [Required]
          [Range(1, 3, ErrorMessage = "Value must be between 1 and 3")]
        public int Priority { get; set; }
          [Required]
          [Range(0, 100, ErrorMessage = "Value must be between 0 and 100")]
        public int Progress { get; set; }
        [DisplayFormat(ApplyFormatInEditMode = false, DataFormatString = "{0:dd/MM/yyyy}")]
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public string AssignedTo { get; set; }
         [DisplayFormat(ApplyFormatInEditMode = false, DataFormatString = "{0:dd/MM/yyyy}")]
        public Nullable<System.DateTime> Deadline { get; set; }
        public string Notes { get; set; }
        public bool Active { get; set; }
    }
}
