//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MI_WorkPlan.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class WebAppsEntities : DbContext
    {
        public WebAppsEntities()
            : base("name=WebAppsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tblMiProject> tblMiProjects { get; set; }
        public DbSet<tblMiProjectTask> tblMiProjectTasks { get; set; }
    
        public virtual ObjectResult<Workplan_Search_Result> Workplan_Search(string searchstring)
        {
            var searchstringParameter = searchstring != null ?
                new ObjectParameter("searchstring", searchstring) :
                new ObjectParameter("searchstring", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Workplan_Search_Result>("Workplan_Search", searchstringParameter);
        }
    }
}
